@startuml 

skinparam Shadowing true

title InsertNum - Sequence Diagram

App -> InserisciNumero: inserisci
activate InserisciNumero
InserisciNumero --> App: inserisci(OK)
deactivate InserisciNumero
App -> StackNum: push

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml