@startuml 

skinparam Shadowing true

title InsertNum - Sequence Diagram

CalcController -> InserisciNumero: inserisci
activate InserisciNumero
InserisciNumero --> App: inserisci(OK)
deactivate InserisciNumero
CalcController -> StackNum: push

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml