@startuml classDiagramm
skinparam shadowing true
title Calculator Class Diagramm 

note "Binding per la gestione delle eccezioni" as N1


class StackNum<Complex>{
    - LinkedList <> stackNum
    + push(Complex c) : void 
    + top() : Complex
    + drop() : Complex
    + dup() : void
    + clear() : void
    + over() : void
    + swap() : void
    + toString() : String 
}



class CUI{
    + launch(args) : void
}

class CalcController{
    - view : CalcView
    + initButtons() : void
    + initActions() : void 
}
class CalcView{
    + buttons : Button[]
    + display : TextField
    + stack : TextField/Label : <<da decidere in corso di sviluppo>> 
}

class InserisciNumero{
    + inserisci(String var,StackNum s) : Complex 
}

class Complex{
    - real : double
    - imaginary : double
    + Complex(double real,double imaginary)
    + setReal(double newReal) : void 
    + setImaginary(double newImaginary) : void
    + getReal() : double
    + getImaginary() : double
    + toString() : String
}

class InserisciOperazioni{
    + add(StackNum s) : void
    + sub(StackNum s) : void 
    + mult(StackNum s) : void
    + div(StackNum s) : void
    + sqrt(StackNum s) : void
    + invSign(StackNum s) : void
}

class OperazioniVariabili{
    - LinkedHashMap <char k, Complex c> vars
    + maggX(Complex c,String var) : void
    + minX(Complex c, String var) : void
    + plusX(String var) : Complex
    + lessX(String var) : Complex
}

CUI --> CalcController

CalcController .. N1
CUI .. N1

CalcController --> InserisciOperazioni : <<use>>
CalcController --> InserisciNumero : <<use>>
CalcController --> StackNum : <<use>>
CalcController --> OperazioniVariabili : <<use>>
CalcController o-- CalcView : <<has a>>


InserisciNumero <--> Complex


OperazioniVariabili --> StackNum : <<call>>
InserisciOperazioni --> StackNum : <<call>>
InserisciNumero --> StackNum : <<call>>



@enduml