@startuml CUIClassDiagramm
skinparam shadowing true 

note "Le classi figlie di exception sono tutte eccezioni controllate e gestite dal controller" as N1
class CUI{
    + launch(args) : void
}

class CalcController{
    - view : CalcView
    + initButtons() : void
    + initActions() : void 
}
class CalcView{
    + buttons : Button[]
    + display : TextField
    + stack : TextField/Label : <<da decidere in corso di sviluppo>> 
}

exception Exception{
    + print(msgError) : void
}

exception EmptyStackException{

}

exception InsertVariableException{

}

exception WrongNumberException{

}

exception ArithmeticException{

}

EmptyStackException --|> Exception
InsertVariableException --|> Exception
WrongNumberException --|> Exception
ArithmeticException --|> Exception

EmptyStackException .. N1
InsertVariableException .. N1 
WrongNumberException .. N1
ArithmeticException .. N1


CUI --> CalcController : contains
CalcController -- Exception : handle >
CalcController o-- CalcView : <<has a>>
@enduml