@startuml eccezioni
skinparam actorStyle awesome
skinparam shadowing true
left to right direction

usecase "Inserisci Operazione" as IO 
usecase "Inserisci Numero" as IN 
usecase "Manipolazione Stack" as MS 
usecase "Operazioni sulle variabili" as OV 

usecase "Eccezione Aritmetica" as exc_ari 
usecase "Eccezione Stack Vuoto" as stack_empty
usecase "Eccezione Numero di argomenti errato" as wrong_argumets
usecase "Eccezione Inizializzazione variabile" as GIv

IN <-- wrong_argumets : <<extends>>

IO <-- exc_ari : <<extends>>
IO <-- stack_empty : <<extends>>

MS <-- stack_empty : <<extends>>

OV <-- stack_empty : <<extends>>
OV <-- GIv : <<extends>>

@enduml
