@startuml eccezioni
skinparam actorStyle awesome
skinparam shadowing true
left to right direction

actor "Inserisci Operazione" as IO 
actor "Inserisci Numero" as IN 
actor "Manipolazione Stack" as MS 
actor "Operazioni sulle variabili" as OV 

usecase "Eccezione Aritmetica" as OpeArithmeticException
usecase "Eccezione Stack Vuoto" as EmpyStackException
usecase "Eccezione Numero di argomenti errato" as wrong_argumets
usecase "Eccezione Inizializzazione variabile" as GIv

IN --> wrong_argumets : <<extends>>

IO --> OpeArithmeticException : <<extends>>
IO --> EmptyStackException : <<extends>>

MS --> EmptyStackException : <<extends>>

OV --> EmptyStackException : <<extends>>
OV --> GIv : <<extends>>

@enduml