@startuml 

skinparam Shadowing true

title InsertNum - Sequence Diagram

CUI -> InserisciNumero: inserisci
activate InserisciNumero
InserisciNumero --> CUI: inserisci(OK)
deactivate InserisciNumero
CUI -> StackNum: push

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml