@startuml ActivityDiagram_Inserimento 

start

repeat
: Inserisci numero complex;
: Inserisci numero nello stack;
repeat while(2 inserimenti) is (no)

: Inserisci operazione;
if(Operazione eseguita?) then (yes)
    : Aggiorna stack con risultato;
else (no)
    : ArithmeticException;
endif

stop

@enduml
